import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '@/styles/Home.module.css'
import Search from '@/components/Search'
import AllNews from '../components/AllNews'

export default function Home() {
  return (
    <>
      <Head>
        <title>Investadoodle</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/logo.jpg' />
      </Head>
      <main className={styles.main}>
        <header className={styles.header}>
          <div className={styles.logoContainer}>
            <h1>Investadoodle</h1>
            <img
              src='/logo.jpg'
              alt='Investadoodle Logo'
              className={styles.logo}
            />
          </div>
          <p>Search the latest stock market data and news!</p>
        </header>
        <Search />
        <AllNews />
      </main>
    </>
  )
}
