import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '@/styles/Home.module.css'
import Search from '@/components/Search'
import AllNews from '../components/AllNews'
import EarningsIPOs from '@/components/earningsIPOs'

export default function Home() {
  const [hasError, setHasError] = useState(false)

  const handleError = () => {
    setHasError(true)
    window.alert('Too many requests, please wait a minute and try again.')
  }

  return (
    <>
      <Head>
        <title>Investadoodle</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/chart-line-up.svg' />
      </Head>
      <main className={styles.split}>
        <div className={styles.left}>
          <Search onError={handleError} />
          <EarningsIPOs />
        </div>
        <div class={styles.right}>
          <AllNews />
        </div>
      </main>
    </>
  )
}
