import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import Link from 'next/link'
import StockNews from '../components/StockNews'
import StockStats from '../components/StockStats'

function StockPage() {
  const router = useRouter()
  const { symbol, newsSymbol, description } = router.query
  const decodedDescription = decodeURIComponent(description)

  return (
    <div>
      <Head>
        <title>Investadoodle</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/logo.jpg' />
      </Head>
      <main>
        <header>
          <div className='logoContainer'>
            <h1>Investadoodle</h1>
            <img src='/logo.jpg' alt='Investadoodle Logo' className='logo' />
          </div>
          <p>Search the latest stock market data and news!</p>
          <Link href='/'>Back Home</Link>
        </header>
        <h1>
          {decodedDescription}, {symbol}
        </h1>
        <StockStats symbol={symbol} />
        <StockNews symbol={newsSymbol} />
      </main>
    </div>
  )
}

export default StockPage
