// pages/stock.js
import { useState } from 'react'
import Head from 'next/head'
import { useRouter } from 'next/router'
import Link from 'next/link'
import StockNews from '../components/StockNews'
import StockStats from '../components/StockStats'
import StockChart from '../components/StockChart'

function StockPage() {
  const router = useRouter()
  const { symbol } = router.query
  const [hasError, setHasError] = useState(false)

  const handleError = () => {
    setHasError(true)
    window.alert('Too many requests, please wait a minute and try again.')
    router.push('/')
  }

  return (
    <div>
      <Head>
        <title>Investadoodle</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/logo.jpg' />
      </Head>
      <main>
        <header>
          <div className='logoContainer'>
            <h1>Investadoodle</h1>
            <img src='/logo.jpg' alt='Investadoodle Logo' className='logo' />
          </div>
          <p>Search the latest stock market data and news!</p>
          <Link href='/'>Back Home</Link>
        </header>
        <h1 className='stockPageH1'>{symbol}</h1>
        <StockChart symbol={symbol} onError={handleError} />
        <StockStats symbol={symbol} onError={handleError} />
        <StockNews symbol={symbol} onError={handleError} />
      </main>
    </div>
  )
}

export default StockPage
